modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="ability_progression"
version="2.2.0-1.20.1"
displayName="Custom Ability Progression"
authors="Warcar"
description='''
Datapack centered mod that allows setting requirements for abilities in Mine Mine no Mi.
'''

[[dependencies.ability_progression]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.ability_progression]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.ability_progression]]
modId="mineminenomi"
mandatory=true
versionRange="[0.11.0,)"
ordering="NONE"
side="BOTH"
